// Generated by scripts/build-fixture.mjs from scripts/fixtures/cases.json. Do not edit.
export const CASES: any = {
 "_doc": "Expected outputs for docs/contract-0.4.md. logic.test.ts (through mod/tests/fixtures/cases.ts, baked by scripts/build-fixture.mjs) and `xref.py selftest` run every section. levelOf/evaluate ledgers are v2 parts, merged with the §1 load function.",
 "fingerprint": [
  {
   "text": "System MUST send a single-use link that expires after 15 minutes.",
   "normalized": "system must send a single-use link that expires after 15 minutes",
   "sha256": "1774daf6db767e702d941092e1ff959730a6c37e66306035fe765e2ca80094ba"
  },
  {
   "text": "  System   MUST send a single-use link that expires after 15 minutes ",
   "normalized": "system must send a single-use link that expires after 15 minutes",
   "sha256": "1774daf6db767e702d941092e1ff959730a6c37e66306035fe765e2ca80094ba"
  },
  {
   "text": "Users MUST be able to request a login link by entering their email address.",
   "normalized": "users must be able to request a login link by entering their email address",
   "sha256": "cfcfa463c05da98b5f2a297744bb005d5e277e2eac6aa59ab30cc0d475eaaf93"
  },
  {
   "text": "Größe: ÄÖÜ ß — straße",
   "normalized": "größe: äöü ß — straße",
   "sha256": "c0a39877723668fcc79c7288fd0bc927d1826fe6797bd4500997011ade4b7501"
  },
  {
   "text": "",
   "normalized": "",
   "sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
  },
  {
   "text": "Café au lait.",
   "normalized": "café au lait",
   "sha256": "7c413039fbb2248e2b18b98e7a8d4d85bdcac7cd79b9477a0923f97e3a1f2b50"
  },
  {
   "text": "Ｆｕｌｌｗｉｄｔｈ ＦＲ：",
   "normalized": "fullwidth fr",
   "sha256": "725b36fb8b5d056a747e7c6076d5d2daa99f93c3d32729724b437308b6ca7e04"
  },
  {
   "text": "Café au lait",
   "normalized": "café au lait",
   "sha256": "7c413039fbb2248e2b18b98e7a8d4d85bdcac7cd79b9477a0923f97e3a1f2b50"
  }
 ],
 "glob": [
  {
   "pattern": "*.lock",
   "path": "Cargo.lock",
   "match": true
  },
  {
   "pattern": "*.lock",
   "path": "sub/dir/Cargo.lock",
   "match": true
  },
  {
   "pattern": "/dist/",
   "path": "dist/a/b.js",
   "match": true
  },
  {
   "pattern": "/dist/",
   "path": "dist",
   "match": true
  },
  {
   "pattern": "/dist/",
   "path": "src/dist/a.js",
   "match": false
  },
  {
   "pattern": "node_modules/",
   "path": "a/node_modules/x/y.js",
   "match": true
  },
  {
   "pattern": "node_modules/",
   "path": "node_modules/x.js",
   "match": true
  },
  {
   "pattern": "*.config.*",
   "path": "vite.config.ts",
   "match": true
  },
  {
   "pattern": "*.config.*",
   "path": "src/app.config.json",
   "match": true
  },
  {
   "pattern": "*.config.*",
   "path": "config.ts",
   "match": false
  },
  {
   "pattern": "docs/",
   "path": "docs/a.md",
   "match": true
  },
  {
   "pattern": "/docs/",
   "path": "src/docs/a.md",
   "match": false
  },
  {
   "pattern": "/README.md",
   "path": "README.md",
   "match": true
  },
  {
   "pattern": "/README.md",
   "path": "a/README.md",
   "match": false
  },
  {
   "pattern": "src/*.ts",
   "path": "src/a.ts",
   "match": true
  },
  {
   "pattern": "src/*.ts",
   "path": "src/x/a.ts",
   "match": false
  },
  {
   "pattern": "?.txt",
   "path": "a.txt",
   "match": true
  },
  {
   "pattern": "?.txt",
   "path": "ab.txt",
   "match": false
  },
  {
   "pattern": "src/**/*.ts",
   "path": "src/a.ts",
   "match": true
  },
  {
   "pattern": "src/**/*.ts",
   "path": "src/x/y/a.ts",
   "match": true
  },
  {
   "pattern": "a+b(c).ts",
   "path": "a+b(c).ts",
   "match": true
  },
  {
   "pattern": "/.github/workflows/",
   "path": ".github/workflows/ci.yml",
   "match": true
  }
 ],
 "ignoreFile": [
  {
   "text": "# comment\n\nsrc/generated/\nunclear: *.sql\n  unclear:   db/*.json  \n*.bak\n",
   "expected": {
    "exempt": [
     "src/generated/",
     "*.bak"
    ],
    "unclear": [
     "*.sql",
     "db/*.json"
    ]
   }
  }
 ],
 "isTestFile": [
  {
   "path": "tests/auth/token.test.ts",
   "isTest": true
  },
  {
   "path": "src/auth/token.ts",
   "isTest": false
  },
  {
   "path": "src/auth/token.spec.ts",
   "isTest": true
  },
  {
   "path": "pkg/test_login.py",
   "isTest": true
  },
  {
   "path": "pkg/login_test.go",
   "isTest": true
  },
  {
   "path": "app/__tests__/a.js",
   "isTest": true
  },
  {
   "path": "lib/tests/helper.rb",
   "isTest": false
  },
  {
   "path": "test/unit/a.dart",
   "isTest": true
  }
 ],
 "hasRealTests": [
  {
   "text": "import { test } from 'vitest'\ntest.todo('POST /auth/link sends a link')\n",
   "real": false
  },
  {
   "text": "test('issues a token', () => {})\n",
   "real": true
  },
  {
   "text": "describe('x', () => { it.skip('y') })\n",
   "real": true
  },
  {
   "text": "xit('pending')\nit.todo('later')\n",
   "real": false
  },
  {
   "text": "def test_login():\n    pass\n",
   "real": true
  },
  {
   "text": "func TestLogin(t *testing.T) {}\n",
   "real": true
  }
 ],
 "classifyCore": [
  {
   "name": "spec artifact",
   "rel": "specs/001-magic-link-login/tasks.md",
   "snap": {
    "tasks": [
     {
      "id": "T001",
      "done": true,
      "paths": [
       "src/auth/",
       "tests/auth/"
      ],
      "reqs": []
     },
     {
      "id": "T002",
      "done": true,
      "paths": [
       "src/config/mailer.ts"
      ],
      "reqs": []
     },
     {
      "id": "T004",
      "done": false,
      "paths": [
       "src/auth/token.ts"
      ],
      "reqs": [
       "FR-002"
      ]
     },
     {
      "id": "T006",
      "done": false,
      "paths": [
       "src/auth/callback.ts"
      ],
      "reqs": [
       "FR-003"
      ]
     }
    ],
    "reqIds": [
     "FR-001",
     "FR-002",
     "FR-003",
     "FR-004",
     "FR-005"
    ]
   },
   "ledger": {
    "links": {},
    "accepted": [],
    "anchors": []
   },
   "newText": "",
   "rules": null,
   "expected": {
    "verdict": "spec",
    "task": null
   }
  },
  {
   "name": "workflow is not a spec artifact but unclear",
   "rel": ".github/workflows/ci.yml",
   "snap": {
    "tasks": [
     {
      "id": "T001",
      "done": true,
      "paths": [
       "src/auth/",
       "tests/auth/"
      ],
      "reqs": []
     },
     {
      "id": "T002",
      "done": true,
      "paths": [
       "src/config/mailer.ts"
      ],
      "reqs": []
     },
     {
      "id": "T004",
      "done": false,
      "paths": [
       "src/auth/token.ts"
      ],
      "reqs": [
       "FR-002"
      ]
     },
     {
      "id": "T006",
      "done": false,
      "paths": [
       "src/auth/callback.ts"
      ],
      "reqs": [
       "FR-003"
      ]
     }
    ],
    "reqIds": [
     "FR-001",
     "FR-002",
     "FR-003",
     "FR-004",
     "FR-005"
    ]
   },
   "ledger": {
    "links": {},
    "accepted": [],
    "anchors": []
   },
   "newText": "",
   "rules": null,
   "expected": {
    "verdict": "unclear",
    "task": null
   }
  },
  {
   "name": "lockfile exempt",
   "rel": "package-lock.json",
   "snap": {
    "tasks": [
     {
      "id": "T001",
      "done": true,
      "paths": [
       "src/auth/",
       "tests/auth/"
      ],
      "reqs": []
     },
     {
      "id": "T002",
      "done": true,
      "paths": [
       "src/config/mailer.ts"
      ],
      "reqs": []
     },
     {
      "id": "T004",
      "done": false,
      "paths": [
       "src/auth/token.ts"
      ],
      "reqs": [
       "FR-002"
      ]
     },
     {
      "id": "T006",
      "done": false,
      "paths": [
       "src/auth/callback.ts"
      ],
      "reqs": [
       "FR-003"
      ]
     }
    ],
    "reqIds": [
     "FR-001",
     "FR-002",
     "FR-003",
     "FR-004",
     "FR-005"
    ]
   },
   "ledger": {
    "links": {},
    "accepted": [],
    "anchors": []
   },
   "newText": "",
   "rules": null,
   "expected": {
    "verdict": "exempt",
    "task": null
   }
  },
  {
   "name": "nested lockfile exempt",
   "rel": "app/web/yarn.lock",
   "snap": {
    "tasks": [
     {
      "id": "T001",
      "done": true,
      "paths": [
       "src/auth/",
       "tests/auth/"
      ],
      "reqs": []
     },
     {
      "id": "T002",
      "done": true,
      "paths": [
       "src/config/mailer.ts"
      ],
      "reqs": []
     },
     {
      "id": "T004",
      "done": false,
      "paths": [
       "src/auth/token.ts"
      ],
      "reqs": [
       "FR-002"
      ]
     },
     {
      "id": "T006",
      "done": false,
      "paths": [
       "src/auth/callback.ts"
      ],
      "reqs": [
       "FR-003"
      ]
     }
    ],
    "reqIds": [
     "FR-001",
     "FR-002",
     "FR-003",
     "FR-004",
     "FR-005"
    ]
   },
   "ledger": {
    "links": {},
    "accepted": [],
    "anchors": []
   },
   "newText": "",
   "rules": null,
   "expected": {
    "verdict": "exempt",
    "task": null
   }
  },
  {
   "name": "dist exempt",
   "rel": "dist/bundle.js",
   "snap": {
    "tasks": [
     {
      "id": "T001",
      "done": true,
      "paths": [
       "src/auth/",
       "tests/auth/"
      ],
      "reqs": []
     },
     {
      "id": "T002",
      "done": true,
      "paths": [
       "src/config/mailer.ts"
      ],
      "reqs": []
     },
     {
      "id": "T004",
      "done": false,
      "paths": [
       "src/auth/token.ts"
      ],
      "reqs": [
       "FR-002"
      ]
     },
     {
      "id": "T006",
      "done": false,
      "paths": [
       "src/auth/callback.ts"
      ],
      "reqs": [
       "FR-003"
      ]
     }
    ],
    "reqIds": [
     "FR-001",
     "FR-002",
     "FR-003",
     "FR-004",
     "FR-005"
    ]
   },
   "ledger": {
    "links": {},
    "accepted": [],
    "anchors": []
   },
   "newText": "",
   "rules": null,
   "expected": {
    "verdict": "exempt",
    "task": null
   }
  },
  {
   "name": "planned file",
   "rel": "src/auth/token.ts",
   "snap": {
    "tasks": [
     {
      "id": "T001",
      "done": true,
      "paths": [
       "src/auth/",
       "tests/auth/"
      ],
      "reqs": []
     },
     {
      "id": "T002",
      "done": true,
      "paths": [
       "src/config/mailer.ts"
      ],
      "reqs": []
     },
     {
      "id": "T004",
      "done": false,
      "paths": [
       "src/auth/token.ts"
      ],
      "reqs": [
       "FR-002"
      ]
     },
     {
      "id": "T006",
      "done": false,
      "paths": [
       "src/auth/callback.ts"
      ],
      "reqs": [
       "FR-003"
      ]
     }
    ],
    "reqIds": [
     "FR-001",
     "FR-002",
     "FR-003",
     "FR-004",
     "FR-005"
    ]
   },
   "ledger": {
    "links": {},
    "accepted": [],
    "anchors": []
   },
   "newText": "",
   "rules": null,
   "expected": {
    "verdict": "planned",
    "task": "T004"
   }
  },
  {
   "name": "done folder plans nothing new",
   "rel": "src/auth/new.ts",
   "snap": {
    "tasks": [
     {
      "id": "T001",
      "done": true,
      "paths": [
       "src/auth/",
       "tests/auth/"
      ],
      "reqs": []
     },
     {
      "id": "T002",
      "done": true,
      "paths": [
       "src/config/mailer.ts"
      ],
      "reqs": []
     },
     {
      "id": "T004",
      "done": false,
      "paths": [
       "src/auth/token.ts"
      ],
      "reqs": [
       "FR-002"
      ]
     },
     {
      "id": "T006",
      "done": false,
      "paths": [
       "src/auth/callback.ts"
      ],
      "reqs": [
       "FR-003"
      ]
     }
    ],
    "reqIds": [
     "FR-001",
     "FR-002",
     "FR-003",
     "FR-004",
     "FR-005"
    ]
   },
   "ledger": {
    "links": {},
    "accepted": [],
    "anchors": []
   },
   "newText": "",
   "rules": null,
   "expected": {
    "verdict": "unplanned",
    "task": null
   }
  },
  {
   "name": "done task's own file is still planned",
   "rel": "src/config/mailer.ts",
   "snap": {
    "tasks": [
     {
      "id": "T001",
      "done": true,
      "paths": [
       "src/auth/",
       "tests/auth/"
      ],
      "reqs": []
     },
     {
      "id": "T002",
      "done": true,
      "paths": [
       "src/config/mailer.ts"
      ],
      "reqs": []
     },
     {
      "id": "T004",
      "done": false,
      "paths": [
       "src/auth/token.ts"
      ],
      "reqs": [
       "FR-002"
      ]
     },
     {
      "id": "T006",
      "done": false,
      "paths": [
       "src/auth/callback.ts"
      ],
      "reqs": [
       "FR-003"
      ]
     }
    ],
    "reqIds": [
     "FR-001",
     "FR-002",
     "FR-003",
     "FR-004",
     "FR-005"
    ]
   },
   "ledger": {
    "links": {},
    "accepted": [],
    "anchors": []
   },
   "newText": "",
   "rules": null,
   "expected": {
    "verdict": "planned",
    "task": "T002"
   }
  },
  {
   "name": "task link",
   "rel": "src/ui/theme.ts",
   "snap": {
    "tasks": [
     {
      "id": "T001",
      "done": true,
      "paths": [
       "src/auth/",
       "tests/auth/"
      ],
      "reqs": []
     },
     {
      "id": "T002",
      "done": true,
      "paths": [
       "src/config/mailer.ts"
      ],
      "reqs": []
     },
     {
      "id": "T004",
      "done": false,
      "paths": [
       "src/auth/token.ts"
      ],
      "reqs": [
       "FR-002"
      ]
     },
     {
      "id": "T006",
      "done": false,
      "paths": [
       "src/auth/callback.ts"
      ],
      "reqs": [
       "FR-003"
      ]
     }
    ],
    "reqIds": [
     "FR-001",
     "FR-002",
     "FR-003",
     "FR-004",
     "FR-005"
    ]
   },
   "ledger": {
    "links": {
     "src/ui/theme.ts": [
      "T006"
     ]
    },
    "accepted": [],
    "anchors": []
   },
   "newText": "",
   "rules": null,
   "expected": {
    "verdict": "task-linked",
    "task": "T006"
   }
  },
  {
   "name": "requirement link",
   "rel": "src/ui/theme.ts",
   "snap": {
    "tasks": [
     {
      "id": "T001",
      "done": true,
      "paths": [
       "src/auth/",
       "tests/auth/"
      ],
      "reqs": []
     },
     {
      "id": "T002",
      "done": true,
      "paths": [
       "src/config/mailer.ts"
      ],
      "reqs": []
     },
     {
      "id": "T004",
      "done": false,
      "paths": [
       "src/auth/token.ts"
      ],
      "reqs": [
       "FR-002"
      ]
     },
     {
      "id": "T006",
      "done": false,
      "paths": [
       "src/auth/callback.ts"
      ],
      "reqs": [
       "FR-003"
      ]
     }
    ],
    "reqIds": [
     "FR-001",
     "FR-002",
     "FR-003",
     "FR-004",
     "FR-005"
    ]
   },
   "ledger": {
    "links": {
     "src/ui/theme.ts": [
      "FR-004"
     ]
    },
    "accepted": [],
    "anchors": []
   },
   "newText": "",
   "rules": null,
   "expected": {
    "verdict": "linked",
    "task": null
   }
  },
  {
   "name": "plans win over anchors",
   "rel": "src/auth/token.ts",
   "snap": {
    "tasks": [
     {
      "id": "T001",
      "done": true,
      "paths": [
       "src/auth/",
       "tests/auth/"
      ],
      "reqs": []
     },
     {
      "id": "T002",
      "done": true,
      "paths": [
       "src/config/mailer.ts"
      ],
      "reqs": []
     },
     {
      "id": "T004",
      "done": false,
      "paths": [
       "src/auth/token.ts"
      ],
      "reqs": [
       "FR-002"
      ]
     },
     {
      "id": "T006",
      "done": false,
      "paths": [
       "src/auth/callback.ts"
      ],
      "reqs": [
       "FR-003"
      ]
     }
    ],
    "reqIds": [
     "FR-001",
     "FR-002",
     "FR-003",
     "FR-004",
     "FR-005"
    ]
   },
   "ledger": {
    "links": {},
    "accepted": [],
    "anchors": [
     {
      "id": "001-magic-link-login/FR-002",
      "file": "src/auth/token.ts",
      "line": 1
     }
    ]
   },
   "newText": "",
   "rules": null,
   "expected": {
    "verdict": "planned",
    "task": "T004"
   }
  },
  {
   "name": "anchor in the ledger links an unplanned file",
   "rel": "src/other.ts",
   "snap": {
    "tasks": [
     {
      "id": "T001",
      "done": true,
      "paths": [
       "src/auth/",
       "tests/auth/"
      ],
      "reqs": []
     },
     {
      "id": "T002",
      "done": true,
      "paths": [
       "src/config/mailer.ts"
      ],
      "reqs": []
     },
     {
      "id": "T004",
      "done": false,
      "paths": [
       "src/auth/token.ts"
      ],
      "reqs": [
       "FR-002"
      ]
     },
     {
      "id": "T006",
      "done": false,
      "paths": [
       "src/auth/callback.ts"
      ],
      "reqs": [
       "FR-003"
      ]
     }
    ],
    "reqIds": [
     "FR-001",
     "FR-002",
     "FR-003",
     "FR-004",
     "FR-005"
    ]
   },
   "ledger": {
    "links": {},
    "accepted": [],
    "anchors": [
     {
      "id": "FR-001",
      "file": "src/other.ts",
      "line": 3
     }
    ]
   },
   "newText": "",
   "rules": null,
   "expected": {
    "verdict": "linked",
    "task": null
   }
  },
  {
   "name": "anchor in new content links",
   "rel": "src/new.ts",
   "snap": {
    "tasks": [
     {
      "id": "T001",
      "done": true,
      "paths": [
       "src/auth/",
       "tests/auth/"
      ],
      "reqs": []
     },
     {
      "id": "T002",
      "done": true,
      "paths": [
       "src/config/mailer.ts"
      ],
      "reqs": []
     },
     {
      "id": "T004",
      "done": false,
      "paths": [
       "src/auth/token.ts"
      ],
      "reqs": [
       "FR-002"
      ]
     },
     {
      "id": "T006",
      "done": false,
      "paths": [
       "src/auth/callback.ts"
      ],
      "reqs": [
       "FR-003"
      ]
     }
    ],
    "reqIds": [
     "FR-001",
     "FR-002",
     "FR-003",
     "FR-004",
     "FR-005"
    ]
   },
   "ledger": {
    "links": {},
    "accepted": [],
    "anchors": []
   },
   "newText": "// @spec 001-magic-link-login/FR-001\n",
   "rules": null,
   "expected": {
    "verdict": "linked",
    "task": null
   }
  },
  {
   "name": "scenario anchor in new content links",
   "rel": "tests/e2e/login.spec.ts",
   "snap": {
    "tasks": [
     {
      "id": "T009",
      "done": false,
      "paths": [
       "src/a.ts"
      ],
      "reqs": []
     }
    ],
    "reqIds": [
     "FR-001",
     "FR-002",
     "FR-003",
     "FR-004",
     "FR-005"
    ]
   },
   "ledger": {
    "links": {},
    "accepted": [],
    "anchors": []
   },
   "newText": "// @spec US1-AS1\n",
   "rules": null,
   "expected": {
    "verdict": "linked",
    "task": null
   }
  },
  {
   "name": "manifest unclear",
   "rel": "package.json",
   "snap": {
    "tasks": [
     {
      "id": "T001",
      "done": true,
      "paths": [
       "src/auth/",
       "tests/auth/"
      ],
      "reqs": []
     },
     {
      "id": "T002",
      "done": true,
      "paths": [
       "src/config/mailer.ts"
      ],
      "reqs": []
     },
     {
      "id": "T004",
      "done": false,
      "paths": [
       "src/auth/token.ts"
      ],
      "reqs": [
       "FR-002"
      ]
     },
     {
      "id": "T006",
      "done": false,
      "paths": [
       "src/auth/callback.ts"
      ],
      "reqs": [
       "FR-003"
      ]
     }
    ],
    "reqIds": [
     "FR-001",
     "FR-002",
     "FR-003",
     "FR-004",
     "FR-005"
    ]
   },
   "ledger": {
    "links": {},
    "accepted": [],
    "anchors": []
   },
   "newText": "",
   "rules": null,
   "expected": {
    "verdict": "unclear",
    "task": null
   }
  },
  {
   "name": "config unclear",
   "rel": "vite.config.ts",
   "snap": {
    "tasks": [
     {
      "id": "T001",
      "done": true,
      "paths": [
       "src/auth/",
       "tests/auth/"
      ],
      "reqs": []
     },
     {
      "id": "T002",
      "done": true,
      "paths": [
       "src/config/mailer.ts"
      ],
      "reqs": []
     },
     {
      "id": "T004",
      "done": false,
      "paths": [
       "src/auth/token.ts"
      ],
      "reqs": [
       "FR-002"
      ]
     },
     {
      "id": "T006",
      "done": false,
      "paths": [
       "src/auth/callback.ts"
      ],
      "reqs": [
       "FR-003"
      ]
     }
    ],
    "reqIds": [
     "FR-001",
     "FR-002",
     "FR-003",
     "FR-004",
     "FR-005"
    ]
   },
   "ledger": {
    "links": {},
    "accepted": [],
    "anchors": []
   },
   "newText": "",
   "rules": null,
   "expected": {
    "verdict": "unclear",
    "task": null
   }
  },
  {
   "name": "readme unclear",
   "rel": "README.md",
   "snap": {
    "tasks": [
     {
      "id": "T001",
      "done": true,
      "paths": [
       "src/auth/",
       "tests/auth/"
      ],
      "reqs": []
     },
     {
      "id": "T002",
      "done": true,
      "paths": [
       "src/config/mailer.ts"
      ],
      "reqs": []
     },
     {
      "id": "T004",
      "done": false,
      "paths": [
       "src/auth/token.ts"
      ],
      "reqs": [
       "FR-002"
      ]
     },
     {
      "id": "T006",
      "done": false,
      "paths": [
       "src/auth/callback.ts"
      ],
      "reqs": [
       "FR-003"
      ]
     }
    ],
    "reqIds": [
     "FR-001",
     "FR-002",
     "FR-003",
     "FR-004",
     "FR-005"
    ]
   },
   "ledger": {
    "links": {},
    "accepted": [],
    "anchors": []
   },
   "newText": "",
   "rules": null,
   "expected": {
    "verdict": "unclear",
    "task": null
   }
  },
  {
   "name": "no tasks: untracked",
   "rel": "src/a.ts",
   "snap": {
    "tasks": [],
    "reqIds": [
     "FR-001",
     "FR-002",
     "FR-003",
     "FR-004",
     "FR-005"
    ]
   },
   "ledger": {
    "links": {},
    "accepted": [],
    "anchors": []
   },
   "newText": "",
   "rules": null,
   "expected": {
    "verdict": "untracked",
    "task": null
   }
  },
  {
   "name": "no tasks but unclear stays unclear",
   "rel": "package.json",
   "snap": {
    "tasks": [],
    "reqIds": [
     "FR-001",
     "FR-002",
     "FR-003",
     "FR-004",
     "FR-005"
    ]
   },
   "ledger": {
    "links": {},
    "accepted": [],
    "anchors": []
   },
   "newText": "",
   "rules": null,
   "expected": {
    "verdict": "unclear",
    "task": null
   }
  },
  {
   "name": "plain unplanned",
   "rel": "src/ui/theme.ts",
   "snap": {
    "tasks": [
     {
      "id": "T001",
      "done": true,
      "paths": [
       "src/auth/",
       "tests/auth/"
      ],
      "reqs": []
     },
     {
      "id": "T002",
      "done": true,
      "paths": [
       "src/config/mailer.ts"
      ],
      "reqs": []
     },
     {
      "id": "T004",
      "done": false,
      "paths": [
       "src/auth/token.ts"
      ],
      "reqs": [
       "FR-002"
      ]
     },
     {
      "id": "T006",
      "done": false,
      "paths": [
       "src/auth/callback.ts"
      ],
      "reqs": [
       "FR-003"
      ]
     }
    ],
    "reqIds": [
     "FR-001",
     "FR-002",
     "FR-003",
     "FR-004",
     "FR-005"
    ]
   },
   "ledger": {
    "links": {},
    "accepted": [],
    "anchors": []
   },
   "newText": "",
   "rules": null,
   "expected": {
    "verdict": "unplanned",
    "task": null
   }
  },
  {
   "name": "custom exempt via .xrefignore",
   "rel": "src/generated/api.ts",
   "snap": {
    "tasks": [
     {
      "id": "T001",
      "done": true,
      "paths": [
       "src/auth/",
       "tests/auth/"
      ],
      "reqs": []
     },
     {
      "id": "T002",
      "done": true,
      "paths": [
       "src/config/mailer.ts"
      ],
      "reqs": []
     },
     {
      "id": "T004",
      "done": false,
      "paths": [
       "src/auth/token.ts"
      ],
      "reqs": [
       "FR-002"
      ]
     },
     {
      "id": "T006",
      "done": false,
      "paths": [
       "src/auth/callback.ts"
      ],
      "reqs": [
       "FR-003"
      ]
     }
    ],
    "reqIds": [
     "FR-001",
     "FR-002",
     "FR-003",
     "FR-004",
     "FR-005"
    ]
   },
   "ledger": {
    "links": {},
    "accepted": [],
    "anchors": []
   },
   "newText": "",
   "rules": {
    "ignoreFile": "# generated code\nsrc/generated/\nunclear: *.sql\n"
   },
   "expected": {
    "verdict": "exempt",
    "task": null
   }
  },
  {
   "name": "custom unclear via .xrefignore",
   "rel": "db/schema.sql",
   "snap": {
    "tasks": [
     {
      "id": "T001",
      "done": true,
      "paths": [
       "src/auth/",
       "tests/auth/"
      ],
      "reqs": []
     },
     {
      "id": "T002",
      "done": true,
      "paths": [
       "src/config/mailer.ts"
      ],
      "reqs": []
     },
     {
      "id": "T004",
      "done": false,
      "paths": [
       "src/auth/token.ts"
      ],
      "reqs": [
       "FR-002"
      ]
     },
     {
      "id": "T006",
      "done": false,
      "paths": [
       "src/auth/callback.ts"
      ],
      "reqs": [
       "FR-003"
      ]
     }
    ],
    "reqIds": [
     "FR-001",
     "FR-002",
     "FR-003",
     "FR-004",
     "FR-005"
    ]
   },
   "ledger": {
    "links": {},
    "accepted": [],
    "anchors": []
   },
   "newText": "",
   "rules": {
    "ignoreFile": "src/generated/\nunclear: *.sql\n"
   },
   "expected": {
    "verdict": "unclear",
    "task": null
   }
  }
 ],
 "levelOf": {
  "snap": {
   "tasks": [
    {
     "id": "T004",
     "done": true,
     "paths": [
      "src/auth/token.ts"
     ],
     "reqs": [
      "FR-002"
     ]
    },
    {
     "id": "T005",
     "done": false,
     "paths": [
      "src/auth/request-link.ts"
     ],
     "reqs": [
      "FR-001"
     ]
    },
    {
     "id": "T008",
     "done": true,
     "paths": [
      "src/ui/expired-page.tsx"
     ],
     "reqs": [
      "FR-004"
     ]
    },
    {
     "id": "T009",
     "done": true,
     "paths": [
      "src/rate.ts"
     ],
     "reqs": [
      "FR-005"
     ]
    }
   ],
   "reqs": [
    {
     "id": "FR-001",
     "text": "Users MUST be able to request a login link by entering their email address."
    },
    {
     "id": "FR-002",
     "text": "System MUST send a single-use link that expires after 15 minutes."
    },
    {
     "id": "FR-003",
     "text": "System MUST sign the user in when a valid link is opened."
    },
    {
     "id": "FR-004",
     "text": "System MUST reject expired or reused links with a clear message."
    },
    {
     "id": "FR-005",
     "text": "System MUST rate-limit link requests."
    }
   ],
   "realTests": [
    "tests/auth/token.test.ts"
   ],
   "featureDir": "specs/001-magic-link-login"
  },
  "cases": [
   {
    "name": "no task",
    "id": "FR-003",
    "ledger": {
     "map": {},
     "links": {},
     "anchors": [],
     "touched": {},
     "verification": {},
     "fingerprints": {}
    },
    "expected": "specified"
   },
   {
    "name": "open task",
    "id": "FR-001",
    "ledger": {
     "map": {},
     "links": {},
     "anchors": [],
     "touched": {},
     "verification": {},
     "fingerprints": {}
    },
    "expected": "planned"
   },
   {
    "name": "done task, code anchor",
    "id": "FR-002",
    "ledger": {
     "map": {},
     "links": {},
     "anchors": [
      {
       "id": "FR-002",
       "file": "src/auth/token.ts",
       "line": 1
      }
     ],
     "touched": {},
     "verification": {},
     "fingerprints": {}
    },
    "expected": "implemented"
   },
   {
    "name": "done task, touched code",
    "id": "FR-004",
    "ledger": {
     "map": {},
     "links": {},
     "anchors": [],
     "touched": {
      "T008": [
       "src/ui/expired-page.tsx"
      ]
     },
     "verification": {},
     "fingerprints": {}
    },
    "expected": "implemented"
   },
   {
    "name": "done task, only a test file touched",
    "id": "FR-004",
    "ledger": {
     "map": {},
     "links": {},
     "anchors": [],
     "touched": {
      "T008": [
       "tests/ui/expired.test.ts"
      ]
     },
     "verification": {},
     "fingerprints": {}
    },
    "expected": "planned"
   },
   {
    "name": "tested by a real test anchor",
    "id": "FR-002",
    "ledger": {
     "map": {},
     "links": {},
     "anchors": [
      {
       "id": "FR-002",
       "file": "src/auth/token.ts",
       "line": 1
      },
      {
       "id": "001-magic-link-login/FR-002",
       "file": "tests/auth/token.test.ts",
       "line": 1
      }
     ],
     "touched": {},
     "verification": {},
     "fingerprints": {}
    },
    "expected": "tested"
   },
   {
    "name": "anchor in a todo-only test is not tested",
    "id": "FR-005",
    "ledger": {
     "map": {},
     "links": {},
     "anchors": [
      {
       "id": "FR-005",
       "file": "tests/rate.test.ts",
       "line": 1
      }
     ],
     "touched": {
      "T009": [
       "src/rate.ts"
      ]
     },
     "verification": {},
     "fingerprints": {}
    },
    "expected": "implemented"
   },
   {
    "name": "passing with matching fingerprint",
    "id": "FR-002",
    "ledger": {
     "map": {},
     "links": {},
     "anchors": [
      {
       "id": "FR-002",
       "file": "src/auth/token.ts",
       "line": 1
      },
      {
       "id": "FR-002",
       "file": "tests/auth/token.test.ts",
       "line": 1
      }
     ],
     "touched": {},
     "verification": {
      "FR-002": {
       "status": "passing",
       "tests": [
        "t"
       ],
       "at": "",
       "commit": "",
       "fingerprint": "1774daf6db767e702d941092e1ff959730a6c37e66306035fe765e2ca80094ba"
      }
     },
     "fingerprints": {
      "FR-002": "1774daf6db767e702d941092e1ff959730a6c37e66306035fe765e2ca80094ba"
     }
    },
    "expected": "passing"
   },
   {
    "name": "failing stays tested",
    "id": "FR-002",
    "ledger": {
     "map": {},
     "links": {},
     "anchors": [
      {
       "id": "FR-002",
       "file": "src/auth/token.ts",
       "line": 1
      },
      {
       "id": "FR-002",
       "file": "tests/auth/token.test.ts",
       "line": 1
      }
     ],
     "touched": {},
     "verification": {
      "FR-002": {
       "status": "failing",
       "tests": [
        "t"
       ],
       "at": "",
       "commit": "",
       "fingerprint": "1774daf6db767e702d941092e1ff959730a6c37e66306035fe765e2ca80094ba"
      }
     },
     "fingerprints": {}
    },
    "expected": "tested"
   },
   {
    "name": "stale fingerprint caps at planned",
    "id": "FR-002",
    "ledger": {
     "map": {},
     "links": {},
     "anchors": [
      {
       "id": "FR-002",
       "file": "src/auth/token.ts",
       "line": 1
      }
     ],
     "touched": {},
     "verification": {},
     "fingerprints": {
      "FR-002": "0000000000000000000000000000000000000000000000000000000000000000"
     }
    },
    "expected": "planned"
   },
   {
    "name": "mapped task counts",
    "id": "FR-003",
    "ledger": {
     "map": {
      "FR-003": [
       "T008"
      ]
     },
     "links": {},
     "anchors": [],
     "touched": {
      "T008": [
       "src/ui/expired-page.tsx"
      ]
     },
     "verification": {},
     "fingerprints": {}
    },
    "expected": "implemented"
   }
  ]
 },
 "evaluate": {
  "snap": {
   "featureDir": "specs/001-magic-link-login",
   "tasks": [
    {
     "id": "T004",
     "done": true,
     "paths": [
      "src/auth/token.ts"
     ],
     "reqs": [
      "FR-002"
     ]
    },
    {
     "id": "T005",
     "done": false,
     "paths": [
      "src/auth/request-link.ts"
     ],
     "reqs": [
      "FR-001"
     ]
    }
   ],
   "reqs": [
    {
     "id": "FR-001",
     "text": "Users MUST be able to request a login link by entering their email address."
    },
    {
     "id": "FR-002",
     "text": "System MUST send a single-use link that expires after 15 minutes."
    },
    {
     "id": "FR-003",
     "text": "System MUST sign the user in when a valid link is opened."
    },
    {
     "id": "FR-004",
     "text": "System MUST reject expired or reused links with a clear message."
    },
    {
     "id": "FR-005",
     "text": "System MUST rate-limit link requests."
    }
   ],
   "stories": [
    {
     "id": "US1",
     "scenarios": [
      {
       "id": "US1-AS1",
       "text": "Given a, When b, Then c."
      }
     ]
    },
    {
     "id": "US2",
     "scenarios": []
    }
   ],
   "realTests": [
    "tests/auth/token.test.ts"
   ]
  },
  "cases": [
   {
    "name": "clean",
    "ledger": {
     "map": {},
     "links": {},
     "fingerprints": {},
     "accepted": [],
     "touched": {},
     "unplanned": [],
     "verification": {},
     "anchors": [],
     "semantic": null
    },
    "semantic": false,
    "expected": {
     "level": "green",
     "kinds": [],
     "covered": 2,
     "total": 5,
     "notes": [
      "US2 has no acceptance scenarios"
     ]
    }
   },
   {
    "name": "one unplanned",
    "ledger": {
     "map": {},
     "links": {},
     "fingerprints": {},
     "accepted": [],
     "touched": {},
     "unplanned": [
      {
       "file": "src/ui/theme.ts",
       "at": "2026-10-09T10:00:00.000Z",
       "task": null
      }
     ],
     "verification": {},
     "anchors": [],
     "semantic": null
    },
    "semantic": false,
    "expected": {
     "level": "yellow",
     "kinds": [
      "unplanned"
     ],
     "covered": 2,
     "total": 5,
     "notes": [
      "US2 has no acceptance scenarios"
     ]
    }
   },
   {
    "name": "accepted is no finding",
    "ledger": {
     "map": {},
     "links": {},
     "fingerprints": {},
     "accepted": [
      "src/ui/theme.ts"
     ],
     "touched": {},
     "unplanned": [],
     "verification": {},
     "anchors": [],
     "semantic": null
    },
    "semantic": false,
    "expected": {
     "level": "green",
     "kinds": [],
     "covered": 2,
     "total": 5,
     "notes": [
      "US2 has no acceptance scenarios"
     ]
    }
   },
   {
    "name": "three unplanned is red",
    "ledger": {
     "map": {},
     "links": {},
     "fingerprints": {},
     "accepted": [],
     "touched": {},
     "unplanned": [
      {
       "file": "a.ts",
       "at": "2026-10-09T10:00:00.000Z",
       "task": null
      },
      {
       "file": "b.ts",
       "at": "2026-10-09T10:00:00.000Z",
       "task": null
      },
      {
       "file": "c.ts",
       "at": "2026-10-09T10:00:00.000Z",
       "task": null
      }
     ],
     "verification": {},
     "anchors": [],
     "semantic": null
    },
    "semantic": false,
    "expected": {
     "level": "red",
     "kinds": [
      "unplanned",
      "unplanned",
      "unplanned",
      "unplanned"
     ],
     "covered": 2,
     "total": 5,
     "notes": [
      "US2 has no acceptance scenarios"
     ]
    }
   },
   {
    "name": "dangling and orphan test",
    "ledger": {
     "map": {},
     "links": {},
     "fingerprints": {},
     "accepted": [],
     "touched": {},
     "unplanned": [],
     "verification": {},
     "anchors": [
      {
       "id": "FR-009",
       "file": "src/a.ts",
       "line": 1
      },
      {
       "id": "001-magic-link-login/FR-010",
       "file": "tests/a.test.ts",
       "line": 2
      },
      {
       "id": "002-other/FR-099",
       "file": "src/b.ts",
       "line": 1
      },
      {
       "id": "US1-AS1",
       "file": "tests/auth/token.test.ts",
       "line": 3
      }
     ],
     "semantic": null
    },
    "semantic": false,
    "expected": {
     "level": "yellow",
     "kinds": [
      "dangling",
      "orphan-test"
     ],
     "covered": 2,
     "total": 5,
     "notes": [
      "US2 has no acceptance scenarios"
     ]
    }
   },
   {
    "name": "stale fingerprint asks to re-verify",
    "ledger": {
     "map": {},
     "links": {},
     "fingerprints": {
      "FR-002": "0000000000000000000000000000000000000000000000000000000000000000"
     },
     "accepted": [],
     "touched": {},
     "unplanned": [],
     "verification": {},
     "anchors": [],
     "semantic": null
    },
    "semantic": false,
    "expected": {
     "level": "yellow",
     "kinds": [
      "re-verify"
     ],
     "covered": 2,
     "total": 5,
     "notes": [
      "US2 has no acceptance scenarios"
     ]
    }
   },
   {
    "name": "matching fingerprint is quiet",
    "ledger": {
     "map": {},
     "links": {},
     "fingerprints": {
      "FR-002": "1774daf6db767e702d941092e1ff959730a6c37e66306035fe765e2ca80094ba"
     },
     "accepted": [],
     "touched": {},
     "unplanned": [],
     "verification": {},
     "anchors": [],
     "semantic": null
    },
    "semantic": false,
    "expected": {
     "level": "green",
     "kinds": [],
     "covered": 2,
     "total": 5,
     "notes": [
      "US2 has no acceptance scenarios"
     ]
    }
   },
   {
    "name": "LLM verdict ignored without semantic",
    "ledger": {
     "map": {},
     "links": {},
     "fingerprints": {},
     "accepted": [],
     "touched": {},
     "unplanned": [],
     "verification": {},
     "anchors": [],
     "semantic": {
      "score": 30,
      "verdict": "drift",
      "reasons": [
       "adds passwords"
      ],
      "changes": [
       {
        "text": "also allow passwords",
        "kind": "contradicts"
       }
      ],
      "at": "2026-10-09T10:00:00.000Z"
     }
    },
    "semantic": false,
    "expected": {
     "level": "green",
     "kinds": [],
     "covered": 2,
     "total": 5,
     "notes": [
      "US2 has no acceptance scenarios"
     ]
    }
   },
   {
    "name": "LLM verdict counts with semantic",
    "ledger": {
     "map": {},
     "links": {},
     "fingerprints": {},
     "accepted": [],
     "touched": {},
     "unplanned": [],
     "verification": {},
     "anchors": [],
     "semantic": {
      "score": 30,
      "verdict": "drift",
      "reasons": [
       "adds passwords"
      ],
      "changes": [
       {
        "text": "also allow passwords",
        "kind": "contradicts"
       }
      ],
      "at": "2026-10-09T10:00:00.000Z"
     }
    },
    "semantic": true,
    "expected": {
     "level": "red",
     "kinds": [
      "semantic",
      "intent"
     ],
     "covered": 2,
     "total": 5,
     "notes": [
      "US2 has no acceptance scenarios"
     ]
    }
   },
   {
    "name": "mapped requirement is covered",
    "ledger": {
     "map": {
      "FR-003": [
       "T005"
      ]
     },
     "links": {},
     "fingerprints": {},
     "accepted": [],
     "touched": {},
     "unplanned": [],
     "verification": {},
     "anchors": [],
     "semantic": null
    },
    "semantic": false,
    "expected": {
     "level": "green",
     "kinds": [],
     "covered": 3,
     "total": 5,
     "notes": [
      "US2 has no acceptance scenarios"
     ]
    }
   }
  ]
 },
 "scenarios": [
  {
   "markdown": "# Feature Specification: X\n\n### User Story 1 - Request a login link (Priority: P1)\n\nText.\n\n**Acceptance Scenarios**:\n\n1. **Given** a registered email, **When** the user requests a link, **Then** an email with a single-use link is sent.\n2. **Given** an unknown email, **When** the user requests a link, **Then** the same response is shown.\n\n### User Story 2 - Sign in (Priority: P1)\n\nNo scenarios here.\n\n### Edge Cases\n\n1. **Given** nothing, this is not a story scenario.\n",
   "expected": [
    {
     "id": "US1",
     "scenarios": [
      {
       "id": "US1-AS1",
       "text": "Given a registered email, When the user requests a link, Then an email with a single-use link is sent."
      },
      {
       "id": "US1-AS2",
       "text": "Given an unknown email, When the user requests a link, Then the same response is shown."
      }
     ]
    },
    {
     "id": "US2",
     "scenarios": []
    }
   ]
  }
 ],
 "reqStatus": [
  {
   "text": "System MUST send a link. SUPERSEDED by FR-006",
   "status": "superseded",
   "supersededBy": "FR-006"
  },
  {
   "text": "RETIRED: social login is out of scope",
   "status": "retired",
   "supersededBy": null
  },
  {
   "text": "System MUST rate-limit link requests.",
   "status": "active",
   "supersededBy": null
  },
  {
   "text": "Retired users MUST re-register.",
   "status": "active",
   "supersededBy": null
  }
 ],
 "junit": [
  {
   "xml": "<?xml version=\"1.0\"?>\n<testsuites><testsuite name=\"auth\">\n<testcase classname=\"auth.token\" name=\"FR-002 issues a single-use token\" file=\"tests/auth/token.test.ts\" time=\"0.01\"/>\n<testcase classname=\"auth.request\" name=\"sends a link &amp; logs\" file=\"tests/auth/request-link.test.ts\"><failure message=\"boom\">x</failure></testcase>\n<testcase classname=\"auth.rate\" name=\"US1-AS2 same response\" file=\"tests/auth/rate.test.ts\"><skipped/></testcase>\n<testcase classname=\"auth.flow\" name=\"callback works\" file=\"tests/auth/callback.test.ts\"></testcase>\n</testsuite></testsuites>\n",
   "expectedCases": [
    {
     "name": "FR-002 issues a single-use token",
     "classname": "auth.token",
     "file": "tests/auth/token.test.ts",
     "status": "passed"
    },
    {
     "name": "sends a link & logs",
     "classname": "auth.request",
     "file": "tests/auth/request-link.test.ts",
     "status": "failed"
    },
    {
     "name": "US1-AS2 same response",
     "classname": "auth.rate",
     "file": "tests/auth/rate.test.ts",
     "status": "skipped"
    },
    {
     "name": "callback works",
     "classname": "auth.flow",
     "file": "tests/auth/callback.test.ts",
     "status": "passed"
    }
   ],
   "anchors": [
    {
     "id": "FR-001",
     "file": "tests/auth/request-link.test.ts",
     "line": 1
    },
    {
     "id": "001-magic-link-login/FR-002",
     "file": "tests/auth/request-link.test.ts",
     "line": 2
    },
    {
     "id": "FR-003",
     "file": "tests/auth/callback.test.ts",
     "line": 1
    }
   ],
   "fingerprints": {
    "FR-001": "f1",
    "FR-002": "f2",
    "FR-003": "f3"
   },
   "at": "2026-10-09T12:00:00.000Z",
   "commit": "abc1234",
   "expectedVerification": {
    "FR-001": {
     "status": "failing",
     "tests": [
      "auth.request.sends a link & logs"
     ],
     "at": "2026-10-09T12:00:00.000Z",
     "commit": "abc1234",
     "fingerprint": "f1"
    },
    "FR-002": {
     "status": "failing",
     "tests": [
      "auth.request.sends a link & logs",
      "auth.token.FR-002 issues a single-use token"
     ],
     "at": "2026-10-09T12:00:00.000Z",
     "commit": "abc1234",
     "fingerprint": "f2"
    },
    "FR-003": {
     "status": "passing",
     "tests": [
      "auth.flow.callback works"
     ],
     "at": "2026-10-09T12:00:00.000Z",
     "commit": "abc1234",
     "fingerprint": "f3"
    }
   },
   "featureDir": "specs/001-magic-link-login"
  }
 ],
 "featureFromBranch": [
  {
   "branch": "001-magic-link-login",
   "dirs": [
    "specs/001-magic-link-login",
    "specs/002-export"
   ],
   "expected": "specs/001-magic-link-login"
  },
  {
   "branch": "feature/002-export-csv",
   "dirs": [
    "specs/001-magic-link-login",
    "specs/002-export"
   ],
   "expected": "specs/002-export"
  },
  {
   "branch": "main",
   "dirs": [
    "specs/001-magic-link-login"
   ],
   "expected": null
  },
  {
   "branch": "003-x",
   "dirs": [
    "specs/001-a"
   ],
   "expected": null
  },
  {
   "branch": "004-y",
   "dirs": [
    "specs/004-a",
    "specs/004-b"
   ],
   "expected": null
  }
 ],
 "migrateV1": [
  {
   "v1": {
    "schema_version": 1,
    "producer": "speckit-xref",
    "feature": "specs/001-magic-link-login",
    "updated_at": "2026-10-09T10:00:00.000Z",
    "summary": {
     "level": "yellow"
    },
    "tasks": {
     "T004": {
      "touched": [
       "src/auth/token.ts"
      ],
      "linked": [
       "tests/auth/token.test.ts"
      ]
     },
     "T005": {
      "touched": [],
      "linked": []
     }
    },
    "requirements": {
     "FR-002": {
      "tasks": [
       "T004"
      ],
      "files": [
       "tests/auth/token.test.ts"
      ],
      "sources": [
       "llm",
       "link"
      ]
     },
     "FR-005": {
      "tasks": [],
      "files": [],
      "sources": [
       "llm"
      ]
     }
    },
    "unplanned": [
     {
      "file": "src/ui/theme.ts",
      "at": "2026-10-09T10:01:00.000Z",
      "task": "T004",
      "acknowledged": false
     },
     {
      "file": "src/x.ts",
      "at": "2026-10-09T10:02:00.000Z",
      "task": null,
      "acknowledged": true
     }
    ],
    "intents": [
     {
      "at": "2026-10-09T10:00:00.000Z",
      "text": "setz T004 um",
      "task": "T004",
      "status": "logged"
     }
    ],
    "anchors": [
     {
      "id": "001-magic-link-login/FR-002",
      "file": "src/auth/token.ts",
      "line": 1
     }
    ],
    "semantic": null
   },
   "committed": {
    "schema_version": 2,
    "feature": "specs/001-magic-link-login",
    "map": {
     "FR-002": [
      "T004"
     ]
    },
    "links": {
     "tests/auth/token.test.ts": [
      "FR-002",
      "T004"
     ]
    },
    "accepted": [
     "src/x.ts"
    ],
    "fingerprints": {}
   },
   "local": {
    "schema_version": 2,
    "feature": "specs/001-magic-link-login",
    "touched": {
     "T004": [
      "src/auth/token.ts"
     ]
    },
    "unplanned": [
     {
      "file": "src/ui/theme.ts",
      "at": "2026-10-09T10:01:00.000Z",
      "task": "T004"
     }
    ],
    "intents": [
     {
      "at": "2026-10-09T10:00:00.000Z",
      "text": "setz T004 um",
      "task": "T004",
      "status": "logged"
     }
    ],
    "semantic": null,
    "semanticHistory": [],
    "verification": {},
    "approvals": {},
    "decisions": [],
    "anchors": [
     {
      "id": "001-magic-link-login/FR-002",
      "file": "src/auth/token.ts",
      "line": 1
     }
    ]
   }
  }
 ]
}
