// Plugin tests cannot read files, so the demo Spec Kit project is baked into a module they import.
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'

const root = new URL('../examples/demo/', import.meta.url).pathname
const out = new URL('../mod/tests/fixtures/demo.ts', import.meta.url).pathname
const files = {}
const walk = dir => {
  for (const name of readdirSync(dir).sort()) {
    const path = join(dir, name)
    if (statSync(path).isDirectory()) walk(path)
    else if (name !== 'xref.json') files[relative(root, path)] = readFileSync(path, 'utf8')
  }
}
walk(root)
writeFileSync(out, `// Generated by scripts/build-fixture.mjs from examples/demo. Do not edit.\nexport const DEMO: Record<string, string> = ${JSON.stringify(files, null, 2)}\n`)
console.log(`wrote ${Object.keys(files).length} files to ${relative(process.cwd(), out)}`)
