// Plugin tests cannot read files, so the demo Spec Kit project and the contract's cases are baked into modules they import.
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'

// Default: examples/demo as it stands. A folder given as the first argument stands in for it (a clean copy).
const root = process.argv[2] ? `${process.argv[2].replace(/\/$/, '')}/` : new URL('../examples/demo/', import.meta.url).pathname
const out = new URL('../mod/tests/fixtures/demo.ts', import.meta.url).pathname
const files = {}
const walk = dir => {
  for (const name of readdirSync(dir).sort()) {
    const path = join(dir, name)
    if (statSync(path).isDirectory()) walk(path)
    else if (name !== 'xref.json') files[relative(root, path)] = readFileSync(path, 'utf8')
  }
}
walk(root)
writeFileSync(out, `// Generated by scripts/build-fixture.mjs from examples/demo. Do not edit.\nexport const DEMO: Record<string, string> = ${JSON.stringify(files, null, 2)}\n`)
console.log(`wrote ${Object.keys(files).length} files to ${relative(process.cwd(), out)}`)

// The contract's expected outputs (docs/contract-0.4.md), shared with the extension's selftest.
const cases = readFileSync(new URL('./fixtures/cases.json', import.meta.url), 'utf8')
const casesOut = new URL('../mod/tests/fixtures/cases.ts', import.meta.url).pathname
writeFileSync(casesOut, `// Generated by scripts/build-fixture.mjs from scripts/fixtures/cases.json. Do not edit.\nexport const CASES: any = ${cases.trim()}\n`)
console.log(`wrote ${relative(process.cwd(), casesOut)}`)
